"""empty message

Revision ID: 452a15e1cb14
Revises: 62488f578adf
Create Date: 2022-09-08 15:59:28.295230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452a15e1cb14'
down_revision = '62488f578adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scratches', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scratches', 'content')
    # ### end Alembic commands ###
