"""empty message

Revision ID: 8eea970e7c90
Revises: 452a15e1cb14
Create Date: 2022-09-21 16:01:44.787959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eea970e7c90'
down_revision = '452a15e1cb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scratches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scratches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='scratches_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='scratches_pkey')
    )
    # ### end Alembic commands ###
