"""empty message

Revision ID: 42ac029beb79
Revises: ea18a24965fc
Create Date: 2022-09-23 00:59:12.139964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ac029beb79'
down_revision = 'ea18a24965fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'title')
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('notebooks', sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
