"""empty message

Revision ID: 862f374aed79
Revises: 379c28ccd972
Create Date: 2022-08-02 13:48:39.957036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862f374aed79'
down_revision = '379c28ccd972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('pages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'updated_at')
    op.drop_column('pages', 'created_at')
    # ### end Alembic commands ###
