"""empty message

Revision ID: 644491df8198
Revises: 42ac029beb79
Create Date: 2022-09-23 01:03:26.258609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644491df8198'
down_revision = '42ac029beb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('title', sa.String(length=60), nullable=False))
    op.add_column('pages', sa.Column('title', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'title')
    op.drop_column('notebooks', 'title')
    # ### end Alembic commands ###
