"""empty message

Revision ID: 0f11db561d43
Revises: ffa05342d273
Create Date: 2022-08-08 22:54:13.857552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f11db561d43'
down_revision = 'ba003b478e5f'
# down_revision = '57045566d64b'
# down_revision = 'ffa05342d273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notebooks', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('pages', 'title',
            existing_type=sa.VARCHAR(length=60),
            nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notebooks', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('pages', 'title',
        existing_type=sa.VARCHAR(length=60),
        nullable=True)
    # ### end Alembic commands ###
