"""empty message

Revision ID: b58c88a65a9b
Revises: 8028058edade
Create Date: 2022-09-22 08:37:50.485031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58c88a65a9b'
down_revision = '8028058edade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scratch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scratch', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
