"""empty message

Revision ID: ea18a24965fc
Revises: de0ea74e7953
Create Date: 2022-09-23 00:45:21.440964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea18a24965fc'
down_revision = 'de0ea74e7953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###
