"""empty message

Revision ID: 57045566d64b
Revises: ba003b478e5f
Create Date: 2022-08-04 22:55:12.149197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57045566d64b'
down_revision = 'ba003b478e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
