"""empty message

Revision ID: de0ea74e7953
Revises: 8028058edade
Create Date: 2022-09-23 00:40:40.209986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0ea74e7953'
down_revision = '8028058edade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
