"""empty message

Revision ID: 3ee37a24d2ef
Revises: b58c88a65a9b
Create Date: 2022-09-22 08:38:27.916166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee37a24d2ef'
down_revision = 'b58c88a65a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scratch', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scratch')
    # ### end Alembic commands ###
