"""empty message

Revision ID: 9ade2d032e3b
Revises: 8eea970e7c90
Create Date: 2022-09-21 16:02:03.854629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ade2d032e3b'
down_revision = '8eea970e7c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scratch', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scratch')
    # ### end Alembic commands ###
