"""empty message

Revision ID: 65c5571de97c
Revises: 0f11db561d43
Create Date: 2022-08-13 12:42:40.171779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c5571de97c'
down_revision = '0f11db561d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'title')
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('notebooks', sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
